#! /bin/sh

# bspwm configuration
# ~ github.com/zanderhavgaard/dotfiles

     # _             _
 # ___| |_ __ _ _ __| |_ _   _ _ __
# / __| __/ _` | '__| __| | | | '_ \
# \__ \ || (_| | |  | |_| |_| | |_) |
# |___/\__\__,_|_|   \__|\__,_| .__/
                            # |_|
                   # _ _           _   _
  # __ _ _ __  _ __ | (_) ___ __ _| |_(_) ___  _ __  ___
 # / _` | '_ \| '_ \| | |/ __/ _` | __| |/ _ \| '_ \/ __|
# | (_| | |_) | |_) | | | (_| (_| | |_| | (_) | | | \__ \
 # \__,_| .__/| .__/|_|_|\___\__,_|\__|_|\___/|_| |_|___/
      # |_|   |_|

# set wallpapers
feh --randomize --bg-scale /home/zander/Dropbox/Wallpapers/new

# hotkey daemon
sxhkd &

# compsitor
picom --config /home/zander/dotfiles/picom/picom.conf

# polybar
bash /home/zander/.config/polybar/launch.sh &

# NetworkManager
# nm-applet &

# volume
# volumeicon &

# dropbox
# dropbox start &

# insync
# insync start &

# Private Internet Access VPN
# /opt/piavpn/bin/pia-client &

                       # _ _
 # _ __ ___   ___  _ __ (_) |_ ___  _ __
# | '_ ` _ \ / _ \| '_ \| | __/ _ \| '__|
# | | | | | | (_) | | | | | || (_) | |
# |_| |_| |_|\___/|_| |_|_|\__\___/|_|

                  # __ _                       _   _
  # ___ ___  _ __  / _(_) __ _ _   _ _ __ __ _| |_(_) ___  _ __
 # / __/ _ \| '_ \| |_| |/ _` | | | | '__/ _` | __| |/ _ \| '_ \
# | (_| (_) | | | |  _| | (_| | |_| | | | (_| | |_| | (_) | | | |
 # \___\___/|_| |_|_| |_|\__, |\__,_|_|  \__,_|\__|_|\___/|_| |_|
                       # |___/

if [[ $(hostname) == 'vostok' ]]; then
   bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
elif [[ $(hostname) == 'nostromo' ]]; then
   bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 8 9 10
   bspc monitor DisplayPort-1 -d 1 2 3 4 5 6 7 8 9 10
   bspc monitor DisplayPort-2 -d 1 2 3 4 5 6 7 8 9 10
elif [[ $(hostname) == 'soyuz' ]]; then
   bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
  echo foo
fi

 # _
# | |__  ___ _ ____      ___ __ ___
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \
# | |_) \__ \ |_) \ V  V /| | | | | |
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
          # |_|
                  # __ _                       _   _
  # ___ ___  _ __  / _(_) __ _ _   _ _ __ __ _| |_(_) ___  _ __
 # / __/ _ \| '_ \| |_| |/ _` | | | | '__/ _` | __| |/ _ \| '_ \
# | (_| (_) | | | |  _| | (_| | |_| | | | (_| | |_| | (_) | | | |
 # \___\___/|_| |_|_| |_|\__, |\__,_|_|  \__,_|\__|_|\___/|_| |_|
                       # |___/

bspc config border_width                  2
bspc config window_gap                    10
bspc config top_monocle_padding           -30
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

           # _                     _
  # ___ ___ | | ___  _ __ ___  ___| |__   ___ _ __ ___   ___
 # / __/ _ \| |/ _ \| '__/ __|/ __| '_ \ / _ \ '_ ` _ \ / _ \
# | (_| (_) | | (_) | |  \__ \ (__| | | |  __/ | | | | |  __/
 # \___\___/|_|\___/|_|  |___/\___|_| |_|\___|_| |_| |_|\___|

bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"



                   # _ _           _   _                          _
  # __ _ _ __  _ __ | (_) ___ __ _| |_(_) ___  _ __    _ __ _   _| | ___  ___
 # / _` | '_ \| '_ \| | |/ __/ _` | __| |/ _ \| '_ \  | '__| | | | |/ _ \/ __|
# | (_| | |_) | |_) | | | (_| (_| | |_| | (_) | | | | | |  | |_| | |  __/\__ \
 # \__,_| .__/| .__/|_|_|\___\__,_|\__|_|\___/|_| |_| |_|   \__,_|_|\___||___/
      # |_|   |_|

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
