#!/usr/bin/env python3
"""Generate k8s-manifest.schema.json — the apiVersion/kind dispatcher used by
yaml-language-server on Kubernetes manifests in gitops trees (see languages.toml).

    ./generate.py          # rewrite k8s-manifest.schema.json
    ./generate.py --check  # also HEAD every upstream URL and fail on non-200

Add a kind by appending to ENTRIES. Upstream URL patterns:
  built-in kinds: yannh/kubernetes-json-schema  <kind>-<group>-<version>.json
  CRDs:           datreeio/CRDs-catalog          <group>/<kind lowercase>_<version>.json
Both are the sources kubeconform uses by default.
"""

import json
import sys
import urllib.request
from pathlib import Path

D = "https://raw.githubusercontent.com/datreeio/CRDs-catalog/main"
Y = "https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict"

# (apiVersion, kind, schema url) — the kinds I actually edit
ENTRIES = [
    # built-in kinds
    ("v1", "Namespace", f"{Y}/namespace-v1.json"),
    ("v1", "ServiceAccount", f"{Y}/serviceaccount-v1.json"),
    ("v1", "ConfigMap", f"{Y}/configmap-v1.json"),
    ("v1", "Secret", f"{Y}/secret-v1.json"),
    ("v1", "Service", f"{Y}/service-v1.json"),
    ("apps/v1", "Deployment", f"{Y}/deployment-apps-v1.json"),
    ("batch/v1", "Job", f"{Y}/job-batch-v1.json"),
    ("scheduling.k8s.io/v1", "PriorityClass", f"{Y}/priorityclass-scheduling-v1.json"),
    ("rbac.authorization.k8s.io/v1", "ClusterRole", f"{Y}/clusterrole-rbac-v1.json"),
    ("rbac.authorization.k8s.io/v1", "ClusterRoleBinding", f"{Y}/clusterrolebinding-rbac-v1.json"),
    ("storage.k8s.io/v1", "StorageClass", f"{Y}/storageclass-storage-v1.json"),
    # CRDs
    ("argoproj.io/v1alpha1", "Application", f"{D}/argoproj.io/application_v1alpha1.json"),
    ("external-secrets.io/v1", "ExternalSecret", f"{D}/external-secrets.io/externalsecret_v1.json"),
    ("external-secrets.io/v1", "SecretStore", f"{D}/external-secrets.io/secretstore_v1.json"),
    ("external-secrets.io/v1", "ClusterSecretStore", f"{D}/external-secrets.io/clustersecretstore_v1.json"),
    ("generators.external-secrets.io/v1alpha1", "ECRAuthorizationToken", f"{D}/generators.external-secrets.io/ecrauthorizationtoken_v1alpha1.json"),
    ("gateway.networking.k8s.io/v1", "HTTPRoute", f"{D}/gateway.networking.k8s.io/httproute_v1.json"),
    ("gateway.networking.k8s.io/v1", "Gateway", f"{D}/gateway.networking.k8s.io/gateway_v1.json"),
    ("gateway.networking.k8s.io/v1", "GatewayClass", f"{D}/gateway.networking.k8s.io/gatewayclass_v1.json"),
    ("gateway.envoyproxy.io/v1alpha1", "SecurityPolicy", f"{D}/gateway.envoyproxy.io/securitypolicy_v1alpha1.json"),
    ("gateway.envoyproxy.io/v1alpha1", "EnvoyProxy", f"{D}/gateway.envoyproxy.io/envoyproxy_v1alpha1.json"),
    ("karpenter.sh/v1", "NodePool", f"{D}/karpenter.sh/nodepool_v1.json"),
    ("karpenter.k8s.aws/v1", "EC2NodeClass", f"{D}/karpenter.k8s.aws/ec2nodeclass_v1.json"),
    ("jetstream.nats.io/v1beta2", "Stream", f"{D}/jetstream.nats.io/stream_v1beta2.json"),
    ("jetstream.nats.io/v1beta2", "Consumer", f"{D}/jetstream.nats.io/consumer_v1beta2.json"),
    ("jetstream.nats.io/v1beta2", "Account", f"{D}/jetstream.nats.io/account_v1beta2.json"),
    ("cert-manager.io/v1", "Certificate", f"{D}/cert-manager.io/certificate_v1.json"),
    ("cert-manager.io/v1", "ClusterIssuer", f"{D}/cert-manager.io/clusterissuer_v1.json"),
    ("monitoring.coreos.com/v1", "ServiceMonitor", f"{D}/monitoring.coreos.com/servicemonitor_v1.json"),
    ("monitoring.coreos.com/v1", "PodMonitor", f"{D}/monitoring.coreos.com/podmonitor_v1.json"),
    ("snapshot.storage.k8s.io/v1", "VolumeSnapshotClass", f"{D}/snapshot.storage.k8s.io/volumesnapshotclass_v1.json"),
    ("snapscheduler.backube/v1", "SnapshotSchedule", f"{D}/snapscheduler.backube/snapshotschedule_v1.json"),
    ("postgresql.cnpg.io/v1", "Cluster", f"{D}/postgresql.cnpg.io/cluster_v1.json"),
    ("db.atlasgo.io/v1alpha1", "AtlasSchema", f"{D}/db.atlasgo.io/atlasschema_v1alpha1.json"),
]

OUT = Path(__file__).with_name("k8s-manifest.schema.json")


def build() -> dict:
    return {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$id": "https://github.com/zanderhavgaard/dotfiles/helix/schemas/k8s-manifest.schema.json",
        "title": "Kubernetes manifest",
        "description": (
            "Generated by generate.py — edit ENTRIES there, not this file. Dispatches on apiVersion + kind "
            "to the upstream JSON schema for that resource (yannh/kubernetes-json-schema for built-in kinds, "
            "datreeio CRDs catalog for CRDs). Documents without a `kind` (helm values files) and unknown "
            "kinds are accepted unchanged."
        ),
        "type": "object",
        "allOf": [
            {
                "if": {
                    "properties": {"apiVersion": {"const": api}, "kind": {"const": kind}},
                    "required": ["apiVersion", "kind"],
                },
                "then": {"$ref": url},
            }
            for api, kind, url in ENTRIES
        ],
    }


def check_urls() -> bool:
    ok = True
    for _, kind, url in ENTRIES:
        try:
            with urllib.request.urlopen(urllib.request.Request(url, method="HEAD"), timeout=20) as r:
                status = r.status
        except Exception as e:  # noqa: BLE001
            status = getattr(e, "code", str(e))
        mark = "ok " if status == 200 else "BAD"
        if status != 200:
            ok = False
        print(f"{mark} {status} {kind:<22} {url}")
    return ok


def main() -> int:
    OUT.write_text(json.dumps(build(), indent=2) + "\n")
    print(f"wrote {OUT.relative_to(Path.cwd()) if OUT.is_relative_to(Path.cwd()) else OUT} ({len(ENTRIES)} kinds)")
    if "--check" in sys.argv[1:] and not check_urls():
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
