#!/bin/bash
xrandr --output eDP1 --auto --primary
xrandr --output DP1 --off
xrandr --output DP2 --off
xrandr --output HDMI1 --off
xrandr --output HDMI2 --off
xrandr --output DP2-1 --off
xrandr --output DP2-2 --off
xrandr --output DP2-3 --off
xrandr --output DP1-1 --off
xrandr --output DP1-2 --off
xrandr --output DP1-3 --off
